// <auto-generated />
using System;
using Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
[DbContext(typeof(TeraDbContext))]
[Migration("20251031215411_SincronizarEsquema")]
partial class SincronizarEsquema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entidades.Disponibilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "DiaSemana")
                        .IsUnique();

                    b.ToTable("Disponibilidades");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DiaSemana = 0,
                            Disponible = false,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = -2,
                            DiaSemana = 1,
                            Disponible = true,
                            HoraFin = new TimeSpan(0, 21, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 16, 0, 0, 0),
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = -3,
                            DiaSemana = 2,
                            Disponible = true,
                            HoraFin = new TimeSpan(0, 21, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 16, 0, 0, 0),
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = -4,
                            DiaSemana = 3,
                            Disponible = true,
                            HoraFin = new TimeSpan(0, 21, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 16, 0, 0, 0),
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = -5,
                            DiaSemana = 4,
                            Disponible = true,
                            HoraFin = new TimeSpan(0, 21, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 16, 0, 0, 0),
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = -6,
                            DiaSemana = 5,
                            Disponible = true,
                            HoraFin = new TimeSpan(0, 21, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 16, 0, 0, 0),
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = -7,
                            DiaSemana = 6,
                            Disponible = false,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("Core.Entidades.ObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioTurno")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ObrasSociales", (string)null);
                });

            modelBuilder.Entity("Core.Entidades.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("Core.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Core.Entidades.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asistencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TurnoId");

                    b.ToTable("Sesiones", (string)null);
                });

            modelBuilder.Entity("Core.Entidades.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ObraSocialId")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObraSocialId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("Core.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Core.Entidades.Disponibilidad", b =>
                {
                    b.HasOne("Core.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Entidades.Paciente", b =>
                {
                    b.HasOne("Core.Entidades.ObraSocial", "ObraSocial")
                        .WithMany("Pacientes")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("Core.Entidades.Pago", b =>
                {
                    b.HasOne("Core.Entidades.Turno", "Turno")
                        .WithMany("Pagos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Core.Entidades.Sesion", b =>
                {
                    b.HasOne("Core.Entidades.Paciente", "Paciente")
                        .WithMany("Sesiones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entidades.Turno", "Turno")
                        .WithMany("Sesiones")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Core.Entidades.Turno", b =>
                {
                    b.HasOne("Core.Entidades.ObraSocial", "ObraSocial")
                        .WithMany("Turnos")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Entidades.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraSocial");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Core.Entidades.ObraSocial", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Core.Entidades.Paciente", b =>
                {
                    b.Navigation("Sesiones");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Core.Entidades.Turno", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
